development:
  sessions:
    default:
      database: docker_admin_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: docker_admin_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: docker_admin
      hosts:
        - mongodb:27017
